### Register CUSTOMER
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "email": "customer@test.com",
  "password": "password123",
  "firstName": "Test",
  "lastName": "Customer"
}

###

### Register ADMIN
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "admin123",
  "firstName": "Admin",
  "lastName": "User",
  "role": "ROLE_ADMIN"
}
